spring.datasource.url=jdbc:postgresql://localhost:5432/micro_hydro_db
spring.datasource.username=micro_hydro_user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=GfLxK4wZ2Yx10HaI4pXCUn+eNalY1SQZbHp7HMh0jKUCbXZbsbgrtaaXYs69+hXwwJtuZJBURDkMsO8HV1C6fA==
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=9090
spring.jpa.properties.hibernate.default_schema=public

# For local debugging, also load application-dev.properties
#spring.profiles.active=dev
