spring.datasource.url=jdbc:postgresql://localhost:5432/micro_hydro_db
spring.datasource.username=micro_hydro_user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=your_super_secret_jwt_key
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=9090
